### ISSUE TITLE
Contributing is confusing

### ISSUE THREAD

**Issue by Seven0492** [KanzenTaiwa/rcg#1]
Hey! I found this project through Low Level Learning's code review that just went up.

What you're doing looks great! Big encouragements from me.

But, I noticed some things looking through.

Let's say I wanted to contribute, where do I even start? I have no idea if you prefer git merge vs rebase, if you have a dev branch I can push to, or if they're all protected and I need to fork the repo to then do a merge request to the dev branch, or if the main branch isn't protected and I can just commit whatever way I want it (though it'd be a huge risk since anyone could just go and delete your codebase, recoverable, but not pleasant), and all that other stuff.

Clarifying this in a CONTRIBUTING file, like I found in some projects, would really do wonders both for people like myself, or newbies who have no idea what git even is :P

Oh, and another low-hanging fruit would be to populate your issues trackers, with, well, issues, or stuff that needs to be worked on, but for general discussion I'd recommend activating the 'Discussions' tab somewhere in the settings.

The code review will garner some attention but if it's too hard to find a way to interact with the project (or with you, the maintainer), most will just click away, I don't mean that badly, it's the just the reality of it.

Even if nothing comes from it, it'd still be fun to chat with people, no?

And, before all, thanks for contributing to the Libre and Open Source software movements! Hugely appreciated

**Comment by Seven0492** [comment]
Oops, really am a dummy, skimmed at the end of the README, but, well, the rest of the issue is still relevant though.

**Comment by KanzenTaiwa** [comment]
Thank you so much for this feedback of the project, it's my first truly open source software released on git-hub, I will figure out a little bit more about which is the best way to insert the changes of the community commits into this without getting trouble, I will do this as soon as possible, I noticed that, in a way or other this would happen, If anyone wants to talk to me I have my discord (kanzentaiwa), just add me and lets talk!

**Comment by Seven0492** [comment]
Well then welcome onboard!

And, apart from the current contributing model being vulnerable to trolls, you don't have to worry about anything legal since you put a license on the project before it ever got the light the day, it handles all the legalese for you.

If someone had contributed _before_ the license, now that'd be a mess if the other person was an asshole, but that's not the case here.

**Comment by KanzenTaiwa** [comment]
Well, now I think it's better, I've included a safety measure, before merge people needs to talk with me first and then it can be accept depending of how good it is.
