### ISSUE TITLE
Blurry video in README

### ISSUE THREAD

**Issue by Seven0492** [KanzenTaiwa/rcg#2]
Hey! It's me again.

I noticed that the video in the README is kind off blurry, that's not really important, but it's good eye-candy and gives an idea of what the program looks like.

I recommend using a specialized tool like [asciinema](https://asciinema.org/) to record your terminal sessions, it'll look much better.

**Comment by KanzenTaiwa** [comment]
Yes!, I'm about to change it, I will be rewriting some stuff in README.md and then I will commit the changes, thanks again for the feedback, appreciated!

**Comment by KanzenTaiwa** [comment]
Done here, check it out the new commits
