### ISSUE TITLE
Security: main git branch isn't protected

### ISSUE THREAD

**Issue by Seven0492** [KanzenTaiwa/rcg#3]
Hey!

Like I mentioned in a previous issue about [how to contribute](https://github.com/KanzenTaiwa/rcg/issues/1), I was confused about how one is supposed to contribute to your project, turned out it was because I skipped the README, so my bad, but I do have some concerns I'd like to raise here, like:

- Any troll passing by can delete your codebase, since your main branch isn't protected.
   (well, it's totally recoverable, but it's not pleasant)
* As related to the above, anyone can submit whatever code (or code deletion) they want to the project, without your approval. Since it's said in the contributing section of the README that one should fork and merge their changes back, I assume that's what you really want them to do instead.

I don't think it's _that_ likely someone will bother doing this, but I'd still protect my main branch just for peace of mind, but I guess if you didn't know it wouldn't have bothered you, huh, well sorry for that.

**Comment by KanzenTaiwa** [comment]
I think right now is a little bit more protected, if you see anything that might have a problem, just use issues or discussion, be free as an american bald eagle my friend <3
