### ISSUE TITLE
Proposal: change to contributing guidelines

### ISSUE THREAD

**Issue by Seven0492** [KanzenTaiwa/rcg#4]
Hey! It's me, again, I know, I'm annoying.

So, I'd like to propose here another contributing model that addresses both the issues raised in [this issue](https://github.com/KanzenTaiwa/rcg/issues/3), and some others, it consists of:

- A protected main branch where only you, the maintainer, can push to.
- A protected dev branch where only you, the maintainer, and trusted contributors (listed as 'developers' in Github) can push to, _but_, people can issue a merge request to this branch with their hot new changes, before being merged into main when it's seen as stable.
- A (optionally protected) testing branch where you and other people can test crazy (fun) stuff that you would never in a hundred moons put in your main code, but, if it works out, you can merge into your dev branch for additional testing, or you can just burn it all to the ground when you see it's a clearly bad idea, it's part of the fun of it I suppose.

Feel free to take what I say, take it apart or tweak it as it fits you, no need to be shy!

Edit:

But, yeah, I noticed something odd with your current model, why the email part? Why? I don't really mind it all that much, but it's a hell of a lot of bureaucracy for something that could be easily discussed in the merge request itself.

If you intend to keep the email requirement, I'd really appreciate it if you would specify why in the readme.

**Comment by KanzenTaiwa** [comment]
Thanks for the feedback again and no you aren't annoying me, I think that I'm the only one who is capable of performing merge, commits and etc, into the project, probably I will create a test branch, so we can make things go boom without hurting anyone, which is great, thanks for all the advices man, I'm lovin' it.
