### ISSUE TITLE
Documentation: platform support

### ISSUE THREAD

**Issue by Seven0492** [KanzenTaiwa/rcg#8]
So, you know, I looked through the readme again, to see how things were going, but I saw something strange.

Here's the section that kind-off bothered me, under 'dependencies':
- RCG was created and tested on linux x86_64 based OS, install the [...]

Huhhh.. what's linux x86_64 _based_ OS??

Let's think over it, what information does these kinds of sentences tend to convey:
- The OS it was made on (optionally)
- What platforms it supports
- OS version supported, or, in the case of Linux and potentially Unix, distribution name and version

The reason why some people call Linux -- GNU/Linux, is because it's the kernel that _empowers_ the environment, not the other way around, most of the time, so the stuff you see on the screen, the environment and such, is a vital part of the user experience. It can, and often does introduce bugs and vulnerabilities.

So what works on one distro, might not work on the other, simply because, for example, Debian doesn't have an up-to-date compiler, so it doesn't even build. That's important information, even just mentioning on what distro it was made would help.

Some people basically hand-craft their Linux environments, like people following the [_Linux From Scratch_](https://www.linuxfromscratch.org/) handbook. If they were, they're probably vastly more knowledgeable than either one of us, but even the little things help.

   (tldr: distro's important)

- If it makes kernel API calls, I wouldn't say it's needed, but it's _really_ important to mention the latest supported kernel, or, at least, the latest kernel version it was known to work on, even more so if it uses new, bleeding edge security APIs, like, maybe, randomisation. Your program may expect behavior from an API call that might have changed throughout the kernel's lifetime, for example. Of course, you don't _need_ to do all that homework, but it'd be amazing both for educational purposes and for people who your program, simply breaks, and they want to help fixing it.

And, btw, the architectures not important, for end-users, it's basically a buzzword, if it runs Linux, it abstracts it all away, unless you're doing _really_ low level operations. At least, it's not important to the end-user. If they're running some really exotic architecture, that's doesn't have complete, or official support yet, like ARM, they're likely aware of it and it's they're job to report it in the bug report.

Whoo! I think.. that's about all? Quite the sprint there

But, as you might have noticed, while 'linux x86_64 _based_ OS' sounds funny, it lacks a bit of substance, if nothing else, I hope you learned something.

**Comment by Seven0492** [comment]
Wanting to clarify, there's absolutely no pressure to do any of these things, take it at your own pace and see what works for you.

I make this Saturday afternoon completely in my free time because I think it's interesting and I like writing huge blocks of text no one will ever read in what I'm interested, so, no pressure, it's a pleasure/hobby project, you don't have any expectations to answer to :P

**Comment by unsubtract** [comment]
The README simply states that you just need `ncurses` to build (though it does erroneously refer to GCC and gmake as dependencies). Most people should be able to figure out that any environment with `ncurses` is a supported platform. All of the other information you described would be largely irrelevant for such a small and simple codebase.

I also see no issue with mentioning what sort of system the program was *created* on; this information is separate to what systems are supported.

**Comment by Seven0492** [comment]
I admit, I went a bit overboard on the information.

Though I believe my point still stands, 'linux x86_64 based OS', while it kind-off makes sense, in the sense that a distribution could be described as an environment built around the Linux kernel, mentioning the architecture has more use as a buzzword than anything else. And 'linux based OS' doesn't say much more either, might as well just say Linux instead.

It all comes from the fact that, to me, it just sounds like an unnecessarily long-winded way to say Linux, I even had to double-read it just to make sure I didn't read it wrong.

Linux, plain and simple, would inform just as much, without confusion.

**Comment by KanzenTaiwa** [comment]
Okay I read here some of the messages, I'm going to simplify some of it actually, I think for now only on Linux that it works and maybe on Unix based OS that will work too, but it depends.

**Comment by KanzenTaiwa** [comment]
I will do more tests and gonna tell if it works on other platforms too.

**Comment by KanzenTaiwa** [comment]
Check it out to see the new changes guys
